workflows:
  my-workflow:
    name: ShoppingList
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - ahac.aiken@gmail.com
      scripts:
        - echo 'Post-publish script'
